name: Android Appium CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch

jobs:
  android-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -no-audio -gpu swiftshader_indirect
          disable-animations: true
          script: |
            adb devices
            adb shell getprop sys.boot_completed

      - name: Install Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2

      - name: Run Appium Tests
        run: mvn clean test

      - name: Upload Allure Results
        if: always()
          uses: actions/upload-artifact@v4
          with:
          name: allure-results
          path: allure-results
